apiVersion: v1
kind: Service
metadata:
  name: album-service
spec:
  selector:
    app: album-service
  ports:
  - protocol: TCP
    port: 8002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: album-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: album-service
  template:
    metadata:
      labels:
        app: album-service
    spec:
      containers:
      - name: album-service
        image: gitlab-df-registry.imt-atlantique.fr/devops/devops-s25-g05/album_1:latest
        env:
        - name: DATABASE_NAME
          value: "devops-s25-05-miscA-db"
        - name: AUTH_DATABASE_NAME
          value: "devops-s25-05-miscA-db"
        - name: MONGO_HOST
          value: "mongo.cloud.imta.fr"
        - name: PHOTOGRAPHER_HOST
          value: "photographer-service"
        - name: PHOTO_HOST
          value: "photo-service.default.svc.devops-s25-05"
        - name : PHOTO_PORT
          value: "8001"

        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8002
      imagePullSecrets:
      - name: regcred
